kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
mountOptions:
  - tls
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0b63d788017d56998
  directoryPerms: "775"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
reclaimPolicy: Retain
allowVolumeExpansion: true
